server:
  port: 7941
 
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://admin:zj123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    
spring:
  application:
    name: microservice-consumer-movie-feign-hystrix
 
feign: 
  hystrix: 
    enabled: true