server:
  port: 8200

eureka:
  client:
    service-url:
      defaultZone: http://admin:zj123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}  

spring:
  application:
    name: microservice-hystrix-turbine

turbine:
  aggregator:
    cluster-config: default
  appConfig: microservice-consumer-movie-hystrix,microservice-consumer-movie-feign-hystrix
  cluster-name-expression: "'default'"