spring:
  application:
    name: microservice-gateway-zuul
server:
  port: 7960

eureka:
  client:
    service-url:
      defaultZone: http://admin:zj123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    
zuul:
  routes:
    microservice-provider-user: /user/**
    
    
    
